### PR TITLE
Add factual reporting to icon

### PR DESCRIPTION
**Pull request by johnskopis**
Since adding factual level to sources.json this displays both. The
visual needs some help.

This is the companion to https://github.com/JeffreyATW/mbfc_crawler/pull/3

### CODE REVIEW

**Comment by johnskopis** [comment]
before/after: https://i.imgur.com/MuwBZBo.png :rofl:

**Comment by JeffreyATW** [comment]
Honestly, this makes the icon a lot less useful. If the factual level really does need to be found in the icon, maybe it can show up in a corner as a color indicator (with no text).

The biggest problem with that, of course, is that a green indicator won't show up on top of a Satire icon, and a red indicator won't show up on top of a Right icon.

My recommendation would be to just not do this. I'm open to other approaches, though.

**Comment by johnskopis** [comment]
I completely agree. The icon really doesn't have enough space.  What about using an objective score from 0-100 to determine the background color of the icon while the text would not change?

something like:
bias score:                                                                      
LB = 60                                                                          
( LC | RC ) = 50                                                                 
( L | R ) = 40                                                                   
E = 30                                                                           
                                                                                 
factual score:                                                                   
VH = 40                                                                          
H = 30                                                                           
M = 20                                                                           
L = 10                                                                           

The objective score = factual + bias.
                                                                                 
color scheme:                                                                     
>90: Green = LB + VH                                                             
>80: Light Green = LB + H | (LC | RC) + VH                                       
>70: Orange = LB + M | (LC | RC) + H | (L | R) + VH                     
>60: Light Red = LB + L | (LC | RC) + M | (L | R ) + H | E + (H | VH)                   
<50: Red = LB + NR | ( LC | RC ) + L | (L | R) + (L | M) | E + (L | M)           

or simpler color coding scheme/works for color blind:
>90: BlueGreen(#009e73) = LB + VH                                                             
>80: BlueGreen(#009e73) = LB + H | (LC | RC) + VH                                             
==                                                                               
>70: Purple/pink (#cc79a7)= LB + M | (LC | RC) + H | (L | R) + VH                     
==                                                                               
>60: Orange(#d55e00) = LB + L | (LC | RC) + M | (L | R ) + H | E + (H | VH)                         
<50: Orange(#d55e00) = LB + NR | ( LC | RC ) + L | (L | R) + (L | M) | E + (L | M)          


In this system the background color used has some significance:
* factual/unbiased sites with a greenish color (most often associated with success)
* semi-biased/semi-factual sites with a pink/purple color (between red and blue)
* biased/unfactual sites with a orange color (danger)

**Comment by johnskopis** [comment]
mockup of color + text: https://i.imgur.com/4c99k4t.png

**Comment by johnskopis** [comment]
I codified the poorly described rules (above) and used the color blind scheme. Let me know what you think. Thanks

**Comment by JeffreyATW** [comment]
I still think keeping the color of the bias prominent is important. No one’s going to spend time understanding why colors are slightly different between two sites with the same bias.

I have a better idea: why not show a two-or-three pixel white bar either along one side or the bottom whose length is based on the factual rating? It’s subtle, but I don’t think factual rating is as important as bias.

**Comment by johnskopis** [comment]
I wish you had tried it before deciding you didn't like it. I think it conveys useful information. For example:
bbc.com is green
nytimes.com isn't green
I would never know that nytimes doesn't provide the best quality factual reporting unless I noticed that it wasn't green, prompting me to investigate why.

Does it pass the grandma test? 
Install the plugin in your grandmother's browser and tell her "green is good; pink is ok; orange is bad"
Install the plugin in your grandmother's browser and tell her "
L means the site has a left bias 
LC means the site has a left center bias
C means the site has a centrist bias
RC means the site has a right center bias
R means the site has a right bias
oh and CP is crazy talk, Q is fake news, PS means science, and S is satire
Also, because not all LC sites are the same be sure to check the indicator on the bottom to determine the level of truthiness of the site."

I have spent all the effort I can afford to spend here. It's your plugin (thanks for writing it!) so of course do as you wish. :v:

**Comment by JeffreyATW** [comment]
Maybe there's room for both approaches? I do like the idea that going toward the [upper center](http://www.allgeneralizationsarefalse.com/wp-content/uploads/2017/11/Third-Edition-Full-Hi-Res.jpg) results in a better color while moving toward the lower corners makes things appear orange. In other words, I gave it some extra thought and I think your background color approach makes sense.

That said, many users might still be interested in just knowing whether a site is left-leaning or right-leaning. The browser extension API has a [context menu](https://developer.chrome.com/apps/contextMenus) option that allows for settings to be changed straight from the icon. Maybe we could add this coloring approach as a radio button option.

**Comment by johnskopis** [comment]
I'm not spending any more effort here. Maybe this PR will serve as a point of reference or a prototype or something.

Thanks again for making the plugin. I think it's great the way you took a suboptimal situation and turned it into a solid plugin. I hope it does hold the media to a greater level of accountability.

**Pull request closed without merging**
